# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yannick
email: mail@yfrommherz.ch
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated linguistics graduate with a strong passion for the interface of human and computer languages. Teaching programming to humanities students!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yfrommherz
github_username:  yannickfrommherz

favicon_ico: "icon.png"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

footer_content: "Copyright &copy; 2023 Yannick Frommherz"

color_scheme: dark



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
