# Book settings

title: "Yannick Frommherz"
author: "Yannick Frommherz"
logo: logo.png
copyright: "2023"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

execute:
  execute_notebooks: force
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org 
  thebe: true

repository:
  url: https://github.com/yannickfrommherz/yfrommherz.ch
  path_to_book: "website" 
  branch: "main" 

sphinx:
  config:
    language: de

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  extra_footer: |
    <div>
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This page is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
    </div>

  baseurl: "https://github.com/yannickfrommherz/yfrommherz.ch"

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - html_admonition
    - linkify


